{% set name = "univi" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1baee2a8cd2e11ad4571e5af70c1b3f306c4191e4a079301d93447ae2a35a8d5

build:
  entry_points:
    - univi = univi.cli:main
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - numpy >=1.26
    - scipy >=1.11
    - pandas >=2.1
    - anndata >=0.10
    - scanpy >=1.11
    - pytorch >=2.2
    - scikit-learn >=1.3
    - h5py >=3.10
    - pyyaml >=6.0
    - matplotlib-base >=3.8
    - seaborn >=0.13
    - python-igraph >=0.11
    - leidenalg >=0.10
    - tqdm >=4.66
    - openpyxl >=3.1

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - univi
  commands:
    - python -m pip check
    - python -c "import univi; print(univi.__version__)"

about:
  home: https://github.com/Ashford-A/UniVI
  summary: "UniVI: a scalable multi-modal VAE toolkit for multimodal single-cell data."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ashford-A
